"""Generate the test code for the JSON de/serialization of enums."""

import io
import json
import os
import pathlib
import sys
import textwrap
from typing import List

import aas_core_codegen
import aas_core_codegen.common
import aas_core_codegen.csharp.naming
import aas_core_codegen.naming
import aas_core_codegen.parse
import aas_core_codegen.run
from aas_core_codegen import intermediate
from aas_core_codegen.common import Stripped
from aas_core_codegen.csharp import common as csharp_common

from aas_core_3_0_csharp_testgen.common import load_symbol_table


def main() -> int:
    """Execute the main routine."""
    symbol_table = load_symbol_table()

    # noinspection PyListCreation
    blocks = []  # type: List[str]

    for our_type in symbol_table.our_types:
        if not isinstance(our_type, intermediate.Enumeration):
            continue

        enum_name = aas_core_codegen.csharp.naming.enum_name(our_type.name)

        assert (
            len(our_type.literals) > 0
        ), f"Unexpected enumeration without literals: {our_type.name}"

        literal_value = our_type.literals[0].value
        literal_value_json_str = json.dumps(literal_value)

        blocks.append(
            Stripped(
                f"""\
[Test]
public void Test_round_trip_{enum_name}()
{{
    var node = Nodes.JsonValue.Create(
        {csharp_common.string_literal(literal_value)})
            ?? throw new System.InvalidOperationException(
                "Unexpected null node");

    var parsed = Aas.Jsonization.Deserialize.{enum_name}From(
        node);

    var serialized = Aas.Jsonization.Serialize.{enum_name}ToJsonValue(
        parsed);
    
    Assert.AreEqual(
        {csharp_common.string_literal(literal_value_json_str)},
        serialized.ToJsonString());
}}  // void Test_round_trip_{enum_name}"""
            )
        )

    writer = io.StringIO()
    writer.write(
        """\
/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */

using Aas = AasCore.Aas3_0;  // renamed
using Nodes = System.Text.Json.Nodes;

using NUnit.Framework;  // can't alias

namespace AasCore.Aas3_0.Tests
{
    public class TestJsonizationOfEnums
    {
"""
    )

    for i, block in enumerate(blocks):
        if i > 0:
            writer.write("\n\n")

        writer.write(textwrap.indent(block, "        "))

    writer.write(
        """
    }  // class TestJsonizationOfEnums
}  // namespace AasCore.Aas3_0.Tests

/*
 * This code has been automatically generated by testgen.
 * Do NOT edit or append.
 */
"""
    )

    this_path = pathlib.Path(os.path.realpath(__file__))
    repo_root = this_path.parent.parent.parent

    target_pth = repo_root / "src/AasCore.Aas3_0.Tests/TestJsonizationOfEnums.cs"
    target_pth.write_text(writer.getvalue(), encoding="utf-8")

    return 0


if __name__ == "__main__":
    sys.exit(main())
